DjangoWebProject1/urls.py
"""
Definition of urls for DjangoWebProject1.
"""

from datetime import datetime
from django.urls import path, re_path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView

from app import forms, views

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Вход',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
    path('links/', views.links, name='links'),
    path('newpost/', views.newpost, name='newpost'),
    path('videopost/', views.videopost, name='videopost'),
    path('pool/', views.pool, name='pool'),
    path('registration', views.registration, name='registration'),
    path('blog/', views.blog, name='blog'),
    re_path(r'^(?P<parameter>\d+)/$', views.blogpost, name='blogpost'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.db import models
from .models import Comment
from .models import Blog

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Имя пользователя'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Пароль'}))

class MyRequestForm(forms.Form):
    requestTheme = forms.CharField(max_length=50,
                                   widget=forms.TextInput({
                                       'class' : 'request__theme',
                                       'placeholder' : 'Причина обращения'}))

    requestText = forms.CharField(widget=forms.Textarea({
                                      'class' : 'request__text',
                                      'placeholder' : 'Текст обращения'}))

    requestChoice = forms.ChoiceField(choices = (
        ('1','Проблема с доставкой'),
        ('2','Проблема с покупкой'),
        ('3','Проблема с оплатой'),

        ), widget=forms.Select({
            'class' : 'request__select'
            }),
                                      initial=1
                                      )



    requestMail = forms.EmailField(min_length=7,
                                   widget=forms.TextInput({
                                       'class' : 'request__mail',
                                       'placeholder' : 'Ваш e-mail'}))

    requestRadio = forms.ChoiceField(choices = (
        ('1','Да'),
        ('2','Нет'),

        ), widget=forms.RadioSelect({
            'class' : 'request__radio',

            }),
                                      initial=1
                                      )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text' : 'Комментарий'}


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'description', 'content', 'image',)
        labels = {'title' : "Заголовок", 'description': "Краткое содержание", 'content': "Полное содержание", 'image': "Картинка"}

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Описание</p>

{% endblock %}

app/templates/app/blog.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>

	<div class="container">
		{% for post in posts %}
		<div class="row">
			<div class="col-9">
				<h2>{{post.title}}</h2>
				<h4>{{post.posted}}</h4>
				<p>{{post.description}}</p>
				<a href="{% url 'blogpost' parameter=post.id %}" class="btn btn-primary">Читать полностью</a>
			</div>
		</div>
		{% endfor%}

	</div>

{% endblock %}

app/templates/app/blogpost.html
{% extends "app/layout.html" %}

{% block content %}

	<div class="container">
		<div class="row">
			<div class="col">
                {% if post_l.image and post_l.image.url != '/media/temp.jpg' %}
                    <img src="{{ post_l.image.url }}" alt="Картинка" width="300" height="200"/>
                {% endif %}
				<h2>{{post.title}}</h2>
				<p>{{post.content|linebreaksbr}}</p>
				<a href="{% url 'blog' %}" class="btn btn-primary">Вернуться к блогу</a>
			</div>
		</div>
		<div class="row">
			<div class="col-6">
				{% if user.is_authenticated %}
					<h3>Добавить комментарий</h3>
					<form method="POST"> {% csrf_token %}
						{{ form.as_p }}
						<button type="submit" class="btn btn-primary">Оставить комментарий</button>

					</form>
				{% else %}
					<h3>Для добавления комментария, пожалуйста, авторизируйтесь!</h3>
				{% endif %}
			</div>
		</div>
		{% for comment in comments %}
		<div class="row">
			<div class="col-6">
				<h7>{{comment.date}}</h7>
				<h5>{{comment.author}}</h5>
				<p>{{comment.text|linebreaksbr}}</p>
			</div>
		</div>
		{% endfor %}	



	</div>

{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Поддержка:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Сотрудничество:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block home-content %}
{% load staticfiles %}


<div class="container body-content">
    <h2 class="text-center">Популярные товары</h2>
    <div class="row">
        <div class="col-md-4 news">
             <div class="news__item">
                 <img src="https://www.sportkult.ru/res/shop/goods/1012A151_16370_701_single_.jpeg" alt="Alternate Text" />
                 <h4 class="news__title">Кросовки</h4>
                 <div class="news__text">
                    Красивые, лёгкие, быстрые кроссовки для спортсменов с высоким уровнем подготовки.
Обновлённый верх работает в унисон с движениями вашей стопы.
Анатомичная стелька увеличивает поддержку и общий комфорт.
Уникальная форма Propulsion Trusstic ™ работает как рычаг, способствующий неустанному движению вперёд.
Вставка Duomax ™, интегрированная с внутренней стороны подошвы, поддерживает стопу и предохраняет её от подворота.
Новый пеноматериал и испытанная технология Gel ™ эффективно поглощают ударную нагрузку, возвращая полученную энергию.
Износоустойчивые вставки в подмётке продлевают срок её службы.
                 </div>
             </div>
        </div>
        <div class="col-md-4 news">
             <div class="news__item">
                 <img src="https://all-t-shirts.ru/goods_images/ru118229I1TG0b18e0a2066c83349c9d94f04da926046.jpg" alt="Alternate Text" />
                 <h4 class="news__title">Футболки</h4>
                 <div class="news__text">
                     Рашгард Fixgear идеально подойдет для тренировок в спортивном зале и на открытом воздухе.
Он защищает тело спортсмена от возможных царапин и ссадин, которые могут возникнуть во время тренировки, а также позволяет длительное время поддерживать мышцы в разогретом состоянии.
Рашгард выполнен из ткани Advanced Performance, которая не впитывает влагу и не утяжеляет изделие, но позволяет коже «дышать».
Идеальное соотношение цены и качества.
Оригинальный дизайн в базовой модели с принтом Пиксель!  
                 </div>
             </div>
        </div>
        <div class="col-md-4 news">
             <div class="news__item">
                 <img src="https://sport.gdebirka.ru/image/cache/data/16461/prod_3037044_2-300x300.jpg" alt="Alternate Text" />
                 <h4 class="news__title">Мячики</h4>
                 <div class="news__text">
                    Сувенирный мяч Demix — отличный подарок для любителей футбола. Модель можно использовать для развития игровых навыков у детей.
             </div>
        </div> 
    </div>
 </div>
{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Anteiku coffee</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{% url 'home' %}" class="navbar-brand">
                    <img src="{% static 'app/content/logo.png' %}" height="60" width="60"/>
                    Спорттовары
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'about' %}">О Нас</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <li><a href="{% url 'links' %}">Полезные ссылки</a></li>
                    <li><a href="{% url 'pool' %}">Обратная связь</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                    {% if user.is_superuser %}
                    <li><a href="{% url 'newpost' %}">Добавление статьи</a></li>
                    {% endif %}
                    <li><a href="{% url 'videopost' %}">Видео</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

     {% block home-content %}{% endblock %}
    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer class="footer">
            <div class="footer__copyright">
                <p>&copy; {{ year }} - Anteiku Coffe</p>
            </div>
            <div class="footer__nav">
                <a href="{% url 'pool' %}" class="footer__nav-link">Обратная связь</a>
                <a href="#" class="footer__nav-link">Доставка</a>
                <a href="#" class="footer__nav-link">Оплата</a>
            </div>
        </footer>
    </div>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/links.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}
<h2>{{ title }}</h2>
<a href ="https://www.sportmaster.ru/catalog" target="_blank"> <img src="{% static 'app/content/1.webp' %}" width="100" height="100" alt="Logo 1"/></a>
<a href ="https://www.myprotein.ru" target="_blank"> <img src="{% static 'app/content/2.webp' %}" width="100" height="100" alt="Logo 2"/></a>
<a href ="https://spb.sportpremier.ru" target="_blank"> <img src="{% static 'app/content/3.jpg' %}" width="100" height="100" alt="Logo 3"/></a>


{% endblock %}

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Используйте локальный аккаунт для входа.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Имя пользователя</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Вход" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Пожалуйства, введите корректные данные</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand pointer">Привет, {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'registration' %}">Регистрация</a></li>
    <li><a href="{% url 'login' %}">Вход</a></li>
</ul>

{% endif %}

app/templates/app/newpost.html
{% extends "app/layout.html" %}

{% block content %}

<h3>Добавить статью</h3>
<form method="POST" enctype="multipart/form-data">{% csrf_token %} {#обязательная защита от атак CSRF#}
    <div>
        {{ blogform.as_p }}
        <button type="submit" class="save btn btn-default">Сохранить статью</button>
    </div>
    </form>


{% endblock %}

app/templates/app/pool.html
{% extends "app/layout.html" %}

{% block content %}
{% if form != None %}
<h2>{{ title }}</h2>
<!--<div class="row">-->
<!--	<div class="col-md-8">-->
		<section id="loginForm">
			<form action="." method="post" class="form-horizontal">
				{% csrf_token %}
				<h4>{{ message }}</h4>
				<hr />
				<div class="form-group">
					<label for="" class="request__label">С чем возникла проблема?</label>
					{{ form.requestChoice }}
				</div>
				<div class="form-group">
					<label for="id_username" class="request__label">Краткое описание</label>
					{{ form.requestTheme }}
				</div>
				<div class="form-group">
					<label for="id_password" class="request__label">Опишите проблему</label>
					{{ form.requestText }}
				</div>
				<div class="form-group">
					<label for="" class="request__label">Ваш e-mail:</label>
					{{ form.requestMail }}
				</div>
				<div class="form-group">
					<label for="" class="request__label">Получить ответ на почту?</label>
					{{ form.requestRadio }}
				</div>
				<div class="form-group">
					<input type="submit" value="Отправить" id="b1" class="btn btn-default" />
				</div>

				{% if form.errors %}
				<p class="validation-summary-errors">Пожалуйства, введите корректные данные</p>
				{% endif %}
			</form>
		</section>
<!--	</div>-->
<!--	<div class="col-md-4">
		<section id="socialLoginForm"></section>
	</div>-->
<!--</div>-->
{% else %}
<h2>Ваш отзыв: </h2>
<p>
    <span class="request__label">Проблема: </span> {{ data.choice }}
</p>
<p>
    <span class="request__label">Короткое описание: </span> {{ data.theme }}
</p>
<p>
    <span class="request__label">Описание проблемы: </span> {{ data.text }}
</p>
<p>
    <span class="request__label">Ваш e-mail: </span> {{ data.email }}
</p>
<p>
    <span class="request__label">Получить ответ на почту? </span> {{ data.radio }}
</p>


{% endif %}

{% endblock %}


{% block scripts %}
    <script>

        function tcb() {
            $('#b1').css('color', 'black');
        };

		function bgw() {
			$('#id_requestText').css('background-color', 'white');
		};
		function tcg() {
			$('#b1').css('color', '#3bc552');
        };
        function bgg() {
            $('#id_requestText').css('background-color', '#3bc552');
        };

        $('#b1').mouseover(tcg);
        $('#b1').mouseout(tcb);

        $('#id_requestText').focus(bgg);
        $('#id_requestText').blur(bgw);

            
    </script>


    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/registration.html
{% extends "app/layout.html" %}
{% block content %}
<h2>Регистрация</h2>
<form method="POST">
	{% csrf_token %}
	<div>
		{{ regform.as_p }}
		<button type="submit" class="save btn btn-success">Регистрация</button>
	</div>
</form>
{% endblock %}

app/templates/app/videopost.html
{% extends "app/layout.html" %}

{% block content %}

<div>
    <h1>"Реклама оптом спорт товаров"</h1>
    <video src="/media/11.mp4" controls="controls" width="400" height="300" poster="/media/14.jpg"></video>
</div>
<hr/>
<div>
    <h1>"Реклама спорт товаров "</h1>
    <video src="/media/12.mp4" controls="controls" width="400" height="300" poster="/media/13.jpg"></video>
</div>
{% endblock %}